### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cy17091268302** [PaulSec/API-EZTV.it#14]
test_api=EztvAPI().tv_show('Game of Thrones')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eztv_api.py", line 92, in tv_show
    req = requests.get(URL, timeout=5)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'eztv.ch' doesn't match either of 'ssl2000.cloudflare.com', 'cloudflare.com', '*.cloudflare.com'

**Comment by PaulSec** [comment]
I just fixed it, sorry for that. 

Cheers!

**Comment by cy17091268302** [comment]
Thanks!
